### ISSUE TITLE
Baho

### ISSUE THREAD

**Issue by llquillo** [ThanMatt/py_games#3]
ambaho po nung dev (tantan)

**Comment by ThanMatt** [comment]
sorry na pu, maliligu na pu ako, will close now. reopen if mabahu pa rin aku

**Comment by llquillo** [comment]
<img width="480" alt="image" src="https://user-images.githubusercontent.com/46316916/180458501-34f917dd-b459-4d8f-9b73-9e95983b5bf8.png">

**Comment by ThanMatt** [comment]
Mabango na po ulit ako, will close the issue

**Comment by ThanMatt** [comment]
will close this again, mabango na po ulit ako 😭

**Comment by llquillo** [comment]
I disagree. Ambaho po.

**Comment by ThanMatt** [comment]
close 😭😭😭😭
